// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF2E7cIM4_nBegMPblFeaIQQnVAhorfrE',
    appId: '1:655066408888:web:db3e16955af2ca38b0914d',
    messagingSenderId: '655066408888',
    projectId: 'calorie-tracker-667da',
    authDomain: 'calorie-tracker-667da.firebaseapp.com',
    storageBucket: 'calorie-tracker-667da.firebasestorage.app',
    measurementId: 'G-FMPMDVTPEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7Gq0JPUqxMnN6B-BTOYy3o8Ic52UPVc',
    appId: '1:655066408888:android:07e67ca167dbe0a9b0914d',
    messagingSenderId: '655066408888',
    projectId: 'calorie-tracker-667da',
    storageBucket: 'calorie-tracker-667da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_pGQWeZboE9J591IKqnIpF4R7k38EAJA',
    appId: '1:655066408888:ios:46dd655e0cad11dbb0914d',
    messagingSenderId: '655066408888',
    projectId: 'calorie-tracker-667da',
    storageBucket: 'calorie-tracker-667da.firebasestorage.app',
    iosBundleId: 'com.example.diet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_pGQWeZboE9J591IKqnIpF4R7k38EAJA',
    appId: '1:655066408888:ios:46dd655e0cad11dbb0914d',
    messagingSenderId: '655066408888',
    projectId: 'calorie-tracker-667da',
    storageBucket: 'calorie-tracker-667da.firebasestorage.app',
    iosBundleId: 'com.example.diet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF2E7cIM4_nBegMPblFeaIQQnVAhorfrE',
    appId: '1:655066408888:web:1838048e4a89f450b0914d',
    messagingSenderId: '655066408888',
    projectId: 'calorie-tracker-667da',
    authDomain: 'calorie-tracker-667da.firebaseapp.com',
    storageBucket: 'calorie-tracker-667da.firebasestorage.app',
    measurementId: 'G-21X1BLTN0P',
  );
}
